var files =
[
    [ "_AF_API.top", "__AF__API_8top.html", null ],
    [ "af-ncp.h", "af-ncp_8h.html", "af-ncp_8h" ],
    [ "af-types.h", "af-types_8h.html", "af-types_8h" ],
    [ "af.h", "af_8h.html", "af_8h" ],
    [ "client-api.h", "client-api_8h.html", "client-api_8h" ],
    [ "core-cli.c", "core-cli_8c.html", "core-cli_8c" ],
    [ "core-cli.h", "core-cli_8h.html", "core-cli_8h" ],
    [ "custom-cli.h", "custom-cli_8h.html", "custom-cli_8h" ],
    [ "ember-types.h", "ember-types_8h.html", "ember-types_8h" ],
    [ "error-def.h", "error-def_8h.html", "error-def_8h" ],
    [ "network-cli.c", "network-cli_8c.html", "network-cli_8c" ],
    [ "network-cli.h", "network-cli_8h.html", "network-cli_8h" ],
    [ "option-cli.c", "option-cli_8c.html", "option-cli_8c" ],
    [ "option-cli.h", "option-cli_8h.html", "option-cli_8h" ],
    [ "plugin-cli.c", "plugin-cli_8c.html", null ],
    [ "plugin-cli.h", "plugin-cli_8h.html", "plugin-cli_8h" ],
    [ "security-cli.c", "security-cli_8c.html", "security-cli_8c" ],
    [ "security-cli.h", "security-cli_8h.html", "security-cli_8h" ],
    [ "v2-to-v6-callbacks.py", "v2-to-v6-callbacks_8py.html", "v2-to-v6-callbacks_8py" ],
    [ "xncp.h", "xncp_8h.html", "xncp_8h" ],
    [ "zcl-cli.c", "zcl-cli_8c.html", "zcl-cli_8c" ],
    [ "zcl-cli.h", "zcl-cli_8h.html", "zcl-cli_8h" ],
    [ "zdo-cli.c", "zdo-cli_8c.html", "zdo-cli_8c" ],
    [ "zdo-cli.h", "zdo-cli_8h.html", "zdo-cli_8h" ]
];