var group__ncp__callback =
[
    [ "Framework Callbacks", "group__framework-callbacks.html", "group__framework-callbacks" ],
    [ "Battery Monitor Callbacks", "group__battery-monitor-callbacks.html", "group__battery-monitor-callbacks" ],
    [ "Bulb PWM Driver Callbacks", "group__bulb-pwm-driver-callbacks.html", "group__bulb-pwm-driver-callbacks" ],
    [ "Button Callbacks", "group__button-callbacks.html", "group__button-callbacks" ],
    [ "Button Interface Callbacks", "group__button-interface-callbacks.html", "group__button-interface-callbacks" ],
    [ "Radio Coexistence Callbacks", "group__coexistence-callbacks.html", "group__coexistence-callbacks" ],
    [ "Radio Coexistence Stub Callbacks", "group__coexistence-stub-callbacks.html", "group__coexistence-stub-callbacks" ],
    [ "Coulomb Counter Callbacks", "group__coulomb-counter-callbacks.html", "group__coulomb-counter-callbacks" ],
    [ "Debug Basic Library Callbacks", "group__debug-basic-library-callbacks.html", "group__debug-basic-library-callbacks" ],
    [ "EEPROM Callbacks", "group__eeprom-callbacks.html", "group__eeprom-callbacks" ],
    [ "Zigbee PRO Core Security Library EZSP Command Handlers Callbacks", "group__ezsp-security-callbacks.html", "group__ezsp-security-callbacks" ],
    [ "GPIO Sensor Interface Callbacks", "group__gpio-sensor-callbacks.html", "group__gpio-sensor-callbacks" ],
    [ "HAL Library Callbacks", "group__hal-library-callbacks.html", "group__hal-library-callbacks" ],
    [ "Idle/Sleep Callbacks", "group__idle-sleep-callbacks.html", "group__idle-sleep-callbacks" ],
    [ "Micrium RTOS Callbacks", "group__micrium-rtos-callbacks.html", "group__micrium-rtos-callbacks" ],
    [ "Microphone Codec MSADPCM Callbacks", "group__microphone-codec-msadpcm-callbacks.html", "group__microphone-codec-msadpcm-callbacks" ],
    [ "Microphone IMAADPCM Callbacks", "group__microphone-imaadpcm-callbacks.html", "group__microphone-imaadpcm-callbacks" ],
    [ "Multi-Network Stub Library Callbacks", "group__multi-network-stub-library-callbacks.html", "group__multi-network-stub-library-callbacks" ],
    [ "Multiple RAIL Demo Code Callbacks", "group__multirail-demo-callbacks.html", "group__multirail-demo-callbacks" ],
    [ "NVM3 Library Callbacks", "group__nvm3-callbacks.html", "group__nvm3-callbacks" ],
    [ "Occupancy PYD-1698 Callbacks", "group__occupancy-pyd1698-callbacks.html", "group__occupancy-pyd1698-callbacks" ],
    [ "SB1 Gesture Sensor Callbacks", "group__sb1-gesture-sensor-callbacks.html", "group__sb1-gesture-sensor-callbacks" ],
    [ "STM32F103RET Library Callbacks", "group__stm32f103ret-library-callbacks.html", "group__stm32f103ret-library-callbacks" ],
    [ "Tamper Switch Interface Callbacks", "group__tamper-switch-callbacks.html", "group__tamper-switch-callbacks" ],
    [ "Gateway MQTT Transport Callbacks", "group__transport-mqtt-callbacks.html", "group__transport-mqtt-callbacks" ],
    [ "XNCP Library Callbacks", "group__xncp-callbacks.html", "group__xncp-callbacks" ],
    [ "ZigBee PRO Leaf Library Callbacks", "group__zigbee-pro-leaf-library-callbacks.html", "group__zigbee-pro-leaf-library-callbacks" ],
    [ "Zigbee PRO Stack Library Callbacks", "group__zigbee-pro-stack-callbacks.html", null ],
    [ "Zigbee Pro Stack Alternate Mac Library Callbacks", "group__zigbee-pro-stack-alt-mac-callbacks.html", null ],
    [ "main API Callbacks", "group__main-callbacks.html", "group__main-callbacks" ],
    [ "ncp API Callbacks", "group__ncp-callbacks.html", "group__ncp-callbacks" ],
    [ "power-meter API Callbacks", "group__power-meter-callbacks.html", "group__power-meter-callbacks" ],
    [ "sim-eeprom API Callbacks", "group__sim-eeprom-callbacks.html", "group__sim-eeprom-callbacks" ],
    [ "stack API Callbacks", "group__stack-callbacks.html", "group__stack-callbacks" ]
];