var group__cli =
[
    [ "Attribute Management", "group__attribute.html", "group__attribute" ],
    [ "Building and Sending Messages", "group__build-send-msg.html", "group__build-send-msg" ],
    [ "Endpoint Manipulation", "group__endpoint.html", "group__endpoint" ],
    [ "General", "group__general.html", "group__general" ],
    [ "Global ZCL", "group__zcl-global.html", "group__zcl-global" ],
    [ "Informational", "group__info.html", "group__info" ],
    [ "Network", "group__network.html", "group__network" ],
    [ "Security", "group__security.html", "group__security" ],
    [ "Test Harness", "group__test.html", "group__test" ],
    [ "ZigBee Device Object Commands (ZDO)", "group__zdo.html", "group__zdo" ],
    [ "Cluster Commands: BACnet Protocol Tunnel", "group__bacnet-protocol-tunnel.html", "group__bacnet-protocol-tunnel" ],
    [ "Cluster Commands: Barrier Control", "group__barrier-control.html", "group__barrier-control" ],
    [ "Cluster Commands: Basic", "group__basic.html", "group__basic" ],
    [ "Cluster Commands: Calendar", "group__calendar.html", "group__calendar" ],
    [ "Cluster Commands: Color Control", "group__color-control.html", "group__color-control" ],
    [ "Cluster Commands: Configuration Cluster", "group__configuration-cluster.html", "group__configuration-cluster" ],
    [ "Cluster Commands: Demand Response and Load Control", "group__demand-response-and-load-control.html", "group__demand-response-and-load-control" ],
    [ "Cluster Commands: Device Management", "group__device-management.html", "group__device-management" ],
    [ "Cluster Commands: Door Lock", "group__door-lock.html", "group__door-lock" ],
    [ "Cluster Commands: Events", "group__events.html", "group__events" ],
    [ "Cluster Commands: Generic Tunnel", "group__generic-tunnel.html", "group__generic-tunnel" ],
    [ "Cluster Commands: Groups", "group__groups.html", "group__groups" ],
    [ "Cluster Commands: IAS ACE", "group__ias-ace.html", "group__ias-ace" ],
    [ "Cluster Commands: IAS Zone", "group__ias-zone.html", "group__ias-zone" ],
    [ "Cluster Commands: Identify", "group__identify.html", "group__identify" ],
    [ "Cluster Commands: Level Control", "group__level-control.html", "group__level-control" ],
    [ "Cluster Commands: MFGLIB Cluster", "group__mfglib-cluster.html", "group__mfglib-cluster" ],
    [ "Cluster Commands: Messaging", "group__messaging.html", "group__messaging" ],
    [ "Cluster Commands: On/off", "group__on-off.html", "group__on-off" ],
    [ "Cluster Commands: Poll Control", "group__poll-control.html", "group__poll-control" ],
    [ "Cluster Commands: Power Profile", "group__power-profile.html", "group__power-profile" ],
    [ "Cluster Commands: Prepayment", "group__prepayment.html", "group__prepayment" ],
    [ "Cluster Commands: Price", "group__price.html", "group__price" ],
    [ "Cluster Commands: SL Works With All Hubs", "group__sl-works-with-all-hubs.html", "group__sl-works-with-all-hubs" ],
    [ "Cluster Commands: Scenes", "group__scenes.html", "group__scenes" ],
    [ "Cluster Commands: Simple Metering", "group__simple-metering.html", "group__simple-metering" ],
    [ "Cluster Commands: Thermostat", "group__thermostat.html", "group__thermostat" ],
    [ "Cluster Commands: Tunneling", "group__tunneling.html", "group__tunneling" ],
    [ "Cluster Commands: Window Covering", "group__window-covering.html", "group__window-covering" ],
    [ "Plugin Commands for Bulb Pwm Driver", "group__plugin-bulb-pwm-cli.html", "group__plugin-bulb-pwm-cli" ],
    [ "Plugin Commands: APS Link Key Authorization", "group__plugin-aps-link-key-authorization.html", "group__plugin-aps-link-key-authorization" ],
    [ "Plugin Commands: Address Table", "group__plugin-address-table.html", "group__plugin-address-table" ],
    [ "Plugin Commands: Antenna", "group__plugin-antenna.html", "group__plugin-antenna" ],
    [ "Plugin Commands: BLE", "group__plugin-ble.html", "group__plugin-ble" ],
    [ "Plugin Commands: Barrier Control Server Cluster", "group__plugin-barrier-control-server.html", "group__plugin-barrier-control-server" ],
    [ "Plugin Commands: Button Joining", "group__plugin-button-joining.html", "group__plugin-button-joining" ],
    [ "Plugin Commands: CLI password protection", "group__plugin-cli-password-protection.html", "group__plugin-cli-password-protection" ],
    [ "Plugin Commands: Calendar Client", "group__plugin-calendar-client.html", "group__plugin-calendar-client" ],
    [ "Plugin Commands: Calendar Common", "group__plugin-calendar-common.html", "group__plugin-calendar-common" ],
    [ "Plugin Commands: Calendar Server", "group__plugin-calendar-server.html", "group__plugin-calendar-server" ],
    [ "Plugin Commands: Coexistence", "group__plugin-coexistence.html", "group__plugin-coexistence" ],
    [ "Plugin Commands: Command Relay", "group__plugin-command-relay.html", "group__plugin-command-relay" ],
    [ "Plugin Commands: Comms Hub Function", "group__plugin-comms-hub-function.html", "group__plugin-comms-hub-function" ],
    [ "Plugin Commands: Comms Hub Function (SubGhz)", "group__plugin-comms-hub-function-sub-ghz.html", "group__plugin-comms-hub-function-sub-ghz" ],
    [ "Plugin Commands: Compact Logger", "group__plugin-compact-logger.html", "group__plugin-compact-logger" ],
    [ "Plugin Commands: Concentrator", "group__plugin-concentrator.html", "group__plugin-concentrator" ],
    [ "Plugin Commands: Connection Manager", "group__plugin-connection-manager.html", "group__plugin-connection-manager" ],
    [ "Plugin Commands: Counters", "group__plugin-counters.html", "group__plugin-counters" ],
    [ "critical-message-queue Plugin Commands: Critical Message Queue", "group__plugin.html", "group__plugin" ],
    [ "Plugin Commands: DMP Tuning and Testing", "group__plugin-dmp-tuning.html", "group__plugin-dmp-tuning" ],
    [ "Plugin Commands: Delayed join", "group__plugin-delayed-join.html", "group__plugin-delayed-join" ],
    [ "Plugin Commands: Demand Response and Load Control", "group__plugin-drlc.html", "group__plugin-drlc" ],
    [ "Plugin Commands: Demand Response and Load Control Server", "group__plugin-drlc-server.html", "group__plugin-drlc-server" ],
    [ "Plugin Commands: Device Database", "group__plugin-device-database.html", "group__plugin-device-database" ],
    [ "Plugin Commands: Device Management Client", "group__plugin-device-management-client.html", "group__plugin-device-management-client" ],
    [ "Plugin Commands: Device Management Server", "group__plugin-device-management-server.html", "group__plugin-device-management-server" ],
    [ "Plugin Commands: Device Query Service", "group__plugin-device-query-service.html", "group__plugin-device-query-service" ],
    [ "Plugin Commands: Device Table", "group__plugin-device-table.html", "group__plugin-device-table" ],
    [ "Plugin Commands: Door Lock Server Cluster", "group__plugin-door-lock-server.html", "group__plugin-door-lock-server" ],
    [ "Plugin Commands: EEPROM", "group__plugin-eeprom.html", "group__plugin-eeprom" ],
    [ "Plugin Commands: EZ-Mode Commissioning", "group__plugin-ezmode-commissioning.html", "group__plugin-ezmode-commissioning" ],
    [ "Plugin Commands: Electrical Measurement Server commands", "group__plugin-electrical-measurement-server.html", "group__plugin-electrical-measurement-server" ],
    [ "Plugin Commands: End Device Support", "group__plugin-end-device-support.html", "group__plugin-end-device-support" ],
    [ "Plugin Commands: Events Server", "group__plugin-events-server.html", "group__plugin-events-server" ],
    [ "Plugin Commands: Find and Bind Initiator", "group__plugin-find-and-bind-initiator.html", "group__plugin-find-and-bind-initiator" ],
    [ "Plugin Commands: Find and Bind Target", "group__plugin-find-and-bind-target.html", "group__plugin-find-and-bind-target" ],
    [ "Plugin Commands: Fragmentation", "group__plugin-fragmentation.html", null ],
    [ "Plugin Commands: GBCS Device Log", "group__plugin-gbcs-device-log.html", "group__plugin-gbcs-device-log" ],
    [ "Plugin Commands: GBCS Gas Meter", "group__plugin-gbcs-gas-meter.html", "group__plugin-gbcs-gas-meter" ],
    [ "Plugin Commands: Gas Proxy Function", "group__plugin-gas-proxy-function.html", "group__plugin-gas-proxy-function" ],
    [ "Plugin Commands: Green Power Client", "group__plugin-green-power-client.html", "group__plugin-green-power-client" ],
    [ "Plugin Commands: Green Power Server", "group__plugin-green-power-server.html", "group__plugin-green-power-server" ],
    [ "Plugin Commands: Green Power Test Device", "group__plugin-green-power-test-device.html", "group__plugin-green-power-test-device" ],
    [ "Plugin Commands: Green Power Translation Table", "group__plugin-green-power-translation-table.html", "group__plugin-green-power-translation-table" ],
    [ "Plugin Commands: Groups Server", "group__plugin-groups-server.html", "group__plugin-groups-server" ],
    [ "Plugin Commands: IAS Zone Client", "group__plugin-ias-zone-client.html", "group__plugin-ias-zone-client" ],
    [ "Plugin Commands: IAS Zone Server", "group__plugin-ias-zone-server.html", "group__plugin-ias-zone-server" ],
    [ "Plugin Commands: Identify", "group__plugin-identify.html", "group__plugin-identify" ],
    [ "Plugin Commands: Idle/Sleep", "group__plugin-idle-sleep.html", "group__plugin-idle-sleep" ],
    [ "Plugin Commands: Illuminance Measurement Server commands", "group__plugin-illuminance-measurement-server.html", "group__plugin-illuminance-measurement-server" ],
    [ "Plugin Commands: Interpan", "group__plugin-interpan.html", "group__plugin-interpan" ],
    [ "Plugin Commands: Key Establishment", "group__plugin-key-establishment.html", "group__plugin-key-establishment" ],
    [ "Plugin Commands: Low Voltage Shutdown", "group__plugin-low-voltage-shutdown.html", "group__plugin-low-voltage-shutdown" ],
    [ "Plugin Commands: MPSI", "group__plugin-mpsi.html", "group__plugin-mpsi" ],
    [ "Plugin Commands: Mac address filtering", "group__plugin-mac-address-filtering.html", "group__plugin-mac-address-filtering" ],
    [ "Plugin Commands: Manufacturing Library", "group__plugin-configuration-server.html", "group__plugin-configuration-server" ],
    [ "Plugin Commands: Manufacturing Library CLI", "group__plugin-manufacturing-library-cli.html", "group__plugin-manufacturing-library-cli" ],
    [ "Plugin Commands: Messaging Client", "group__plugin-messaging-client.html", "group__plugin-messaging-client" ],
    [ "Plugin Commands: Messaging Server", "group__plugin-messaging-server.html", "group__plugin-messaging-server" ],
    [ "Plugin Commands: Meter Mirror", "group__plugin-meter-mirror.html", "group__plugin-meter-mirror" ],
    [ "Plugin Commands: Meter Snapshot Server", "group__plugin-meter-snapshot-server.html", "group__plugin-meter-snapshot-server" ],
    [ "Plugin Commands: Multi-Network Price Passthrough", "group__plugin-mn-price-passthrough.html", "group__plugin-mn-price-passthrough" ],
    [ "Plugin Commands: Network Creator", "group__plugin-network-creator.html", "group__plugin-network-creator" ],
    [ "Plugin Commands: Network Creator Security", "group__plugin-network-creator-security.html", "group__plugin-network-creator-security" ],
    [ "Plugin Commands: Network Find", "group__network-find.html", "group__network-find" ],
    [ "Plugin Commands: Network Steering", "group__plugin-network-steering.html", "group__plugin-network-steering" ],
    [ "Plugin Commands: OTA Bootload", "group__plugin-ota-bootload.html", "group__plugin-ota-bootload" ],
    [ "Plugin Commands: OTA Client", "group__plugin-ota-client.html", "group__plugin-ota-client" ],
    [ "Plugin Commands: OTA Server", "group__plugin-ota-server.html", "group__plugin-ota-server" ],
    [ "Plugin Commands: OTA Simple Storage EEPROM", "group__plugin-ota-storage-simple-eeprom.html", null ],
    [ "Plugin Commands: OTA Storage Common", "group__plugin-ota-storage-common.html", "group__plugin-ota-storage-common" ],
    [ "Plugin Commands: PS Store", "group__plugin-psstore.html", "group__plugin-psstore" ],
    [ "Plugin Commands: PYD-1698 Occupancy Sensor CLI", "group__plugin-occupancy-pyd1698-cli.html", "group__plugin-occupancy-pyd1698-cli" ],
    [ "Plugin Commands: Partner Link Key Exchange", "group__plugin-partner-link-key-exchange.html", "group__plugin-partner-link-key-exchange" ],
    [ "Plugin Commands: Poll Control Client", "group__plugin-poll-control-client.html", "group__plugin-poll-control-client" ],
    [ "Plugin Commands: Power Consumption Model CLI", "group__plugin-power-consumption-model.html", "group__plugin-power-consumption-model" ],
    [ "Plugin Commands: Prepayment Server", "group__plugin-prepayment-server.html", "group__plugin-prepayment-server" ],
    [ "Plugin Commands: Price Client", "group__plugin-price-client.html", "group__plugin-price-client" ],
    [ "Plugin Commands: Price Common", "group__plugin-price-common.html", "group__plugin-price-common" ],
    [ "Plugin Commands: Price Server", "group__plugin-price-server.html", "group__plugin-price-server" ],
    [ "Plugin Commands: Relative Humidity Measurement Server commands", "group__plugin-relative-humidity-measurement-server.html", "group__plugin-relative-humidity-measurement-server" ],
    [ "Plugin Commands: Relay Control Server", "group__plugin-relay-control-server.html", "group__plugin-relay-control-server" ],
    [ "Plugin Commands: Reporting", "group__plugin-reporting.html", "group__plugin-reporting" ],
    [ "Plugin Commands: SB1 Gesture Sensor", "group__plugin-sb1-gesture-sensor.html", "group__plugin-sb1-gesture-sensor" ],
    [ "Plugin Commands: Scenes Server", "group__plugin-scenes.html", "group__plugin-scenes" ],
    [ "Plugin Commands: Simple Metering Client", "group__plugin-simple-metering-client.html", "group__plugin-simple-metering-client" ],
    [ "Plugin Commands: Simple Metering Server", "group__plugin-simple-metering-server.html", "group__plugin-simple-metering-server" ],
    [ "Plugin Commands: Simple Metering Server", "group__plugin-metering-server.html", "group__plugin-metering-server" ],
    [ "Plugin Commands: Sleepy Message Queue", "group__plugin-sleepy-message-queue.html", "group__plugin-sleepy-message-queue" ],
    [ "Plugin Commands: Slot Manager", "group__plugin-slot-manager.html", "group__plugin-slot-manager" ],
    [ "Plugin Commands: Smart Energy Registration", "group__plugin-smart-energy-registration.html", "group__plugin-smart-energy-registration" ],
    [ "Plugin Commands: Stack Diagnostics", "group__plugin-stack-diagnostics.html", "group__plugin-stack-diagnostics" ],
    [ "Plugin Commands: Standalone Bootloader Client", "group__plugin-standalone-bootloader-client.html", "group__plugin-standalone-bootloader-client" ],
    [ "Plugin Commands: Standalone Bootloader Server", "group__plugin-standalone-bootloader-server.html", "group__plugin-standalone-bootloader-server" ],
    [ "Plugin Commands: Sub-GHz Client", "group__plugin-sub-ghz-client.html", "group__plugin-sub-ghz-client" ],
    [ "Plugin Commands: Sub-GHz Server", "group__plugin-sub-ghz-server.html", "group__plugin-sub-ghz-server" ],
    [ "Plugin Commands: Temperature Measurement Server commands", "group__plugin-temperature-measurement-server.html", "group__plugin-temperature-measurement-server" ],
    [ "Plugin Commands: Test Harness", "group__plugin-test-harness.html", "group__plugin-test-harness" ],
    [ "Plugin Commands: Throughput", "group__plugin-throughput.html", "group__plugin-throughput" ],
    [ "Plugin Commands: Throughput Legacy", "group__plugin-throughput-legacy.html", "group__plugin-throughput-legacy" ],
    [ "Plugin Commands: Trust Center Backup", "group__plugin-trust-center-backup.html", "group__plugin-trust-center-backup" ],
    [ "Plugin Commands: Tunneling Client", "group__plugin-tunneling-client.html", "group__plugin-tunneling-client" ],
    [ "Plugin Commands: Tunneling Server", "group__plugin-tunneling-server.html", "group__plugin-tunneling-server" ],
    [ "Plugin Commands: Update TC Link Key", "group__plugin-update-tc-link-key.html", "group__plugin-update-tc-link-key" ],
    [ "Plugin Commands: Wwah Connectivity Manager", "group__plugin-wwah-connectivity-manager.html", "group__plugin-wwah-connectivity-manager" ],
    [ "Plugin Commands: Wwah Server", "group__plugin-wwah-server.html", "group__plugin-wwah-server" ],
    [ "Plugin Commands: ZigBee 3.0 Test Harness", "group__plugin-test-harness-z3.html", "group__plugin-test-harness-z3" ],
    [ "Plugin Commands: ZigBee Light Link (ZLL) Commissioning", "group__plugin-zll-commissioning.html", "group__plugin-zll-commissioning" ],
    [ "Plugin Commands: Zigbee Event Logger", "group__plugin-zigbee-event-logger.html", "group__plugin-zigbee-event-logger" ],
    [ "Plugin Commands: em4", "group__plugin-em4.html", "group__plugin-em4" ],
    [ "Utility Commands: Multiple RAIL Demo Code", "group__plugin-multirail.html", "group__plugin-multirail" ],
    [ "EMBER_AF_DOXYGEN_CLI__NETWORK_COMMANDS", "group__cli.html#ga70bf013b1ff53045ffbd8d0508445a7a", null ],
    [ "EMBER_AF_DOXYGEN_CLI__SECURITY_CBKE_COMMANDS", "group__cli.html#ga1e24365f37f3e91845fbb26865f972ae", null ],
    [ "EMBER_AF_DOXYGEN_CLI__SECURITY_CHANGEKEY_COMMANDS", "group__cli.html#ga1c0d6352788bf3c2cbd62ad01d4bdf89", null ],
    [ "EMBER_AF_DOXYGEN_CLI__ZCL_GLOBAL_COMMANDS", "group__cli.html#gaa5e85d9a59d605743745d9c4dae4aef7", null ]
];