Zigbee Application Framework API Reference: network-cli.c File Reference
network-cli.c File Reference
Implementations for network related CLI commands.
#include "app/framework/include/af.h"
#include "app/framework/util/af-main.h"
#include "app/framework/util/util.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/util/zigbee-framework/zigbee-device-common.h"
#include "network-cli.h"
#include "stack/include/network-formation.h"
Macros
#define EMBER_AF_DOXYGEN_CLI__NETWORK_COMMANDS
network form <channel> <power> <panid>
Functions
void networkJoinCommand (void)
void networkRejoinCommand (void)
void networkFormCommand (void)
void networkExtendedPanIdCommand (void)
void networkLeaveCommand (void)
void networkPermitJoinCommand (void)
void findJoinableNetworkCommand (void)
void findUnusedPanIdCommand (void)
void networkChangeChannelCommand (void)
void networkSetCommand (void)
void networkIdCommand (void)
void networkMultiPhyStartCommand (void)
void networkMultiPhyStopCommand (void)
void networkChangeChildTimeoutOptionMaskCommand (void)
void changeKeepAliveModeCommand (void)
void networkInitCommand (void)
void initNetworkParams (EmberNetworkParameters *networkParams)
void networkRejoinDiffDeviceTypeCommand (void)
Variables
EmberCommandEntry networkCommands []
uint8_t emAfCliNetworkIndex = EMBER_AF_DEFAULT_NETWORK_INDEX
Detailed Description
Implementations for network related CLI commands.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Function Documentation
changeKeepAliveModeCommand()
void changeKeepAliveModeCommand (void)
findJoinableNetworkCommand()
void findJoinableNetworkCommand (void)
References emberAfStartSearchForJoinableNetwork().
findUnusedPanIdCommand()
void findUnusedPanIdCommand (void)
References emberAfFindUnusedPanIdAndForm().
initNetworkParams()
void initNetworkParams (EmberNetworkParameters * networkParams)
References emberAfGetFormAndJoinExtendedPanIdCallback(), EmberNetworkParameters::extendedPanId, EmberNetworkParameters::panId, EmberNetworkParameters::radioChannel, and EmberNetworkParameters::radioTxPower.
Referenced by networkFormCommand(), and networkJoinCommand().
networkChangeChannelCommand()
void networkChangeChannelCommand (void)
networkChangeChildTimeoutOptionMaskCommand()
void networkChangeChildTimeoutOptionMaskCommand (void)
networkExtendedPanIdCommand()
void networkExtendedPanIdCommand (void)
References emberAfSetFormAndJoinExtendedPanIdCallback().
networkFormCommand()
void networkFormCommand (void)
References emberAfFormNetwork(), and initNetworkParams().
networkIdCommand()
void networkIdCommand (void)
References emberAfGetEui64(), emberAfGetNodeId(), and emberAfGetPanId().
networkInitCommand()
void networkInitCommand (void)
networkJoinCommand()
void networkJoinCommand (void)
References emberAfJoinNetwork(), and initNetworkParams().
networkLeaveCommand()
void networkLeaveCommand (void)
networkMultiPhyStartCommand()
void networkMultiPhyStartCommand (void)
References EMBER_SUCCESS, and PHY_INDEX_PRO2PLUS.
networkMultiPhyStopCommand()
void networkMultiPhyStopCommand (void)
References EMBER_SUCCESS, and PHY_INDEX_PRO2PLUS.
networkPermitJoinCommand()
void networkPermitJoinCommand (void)
networkRejoinCommand()
void networkRejoinCommand (void)
References EMBER_AF_REJOIN_DUE_TO_CLI_COMMAND, and EMBER_ALL_802_15_4_CHANNELS_MASK.
networkRejoinDiffDeviceTypeCommand()
void networkRejoinDiffDeviceTypeCommand (void)
networkSetCommand()
void networkSetCommand (void)
References emAfCliNetworkIndex.
Variable Documentation
emAfCliNetworkIndex
uint8_t emAfCliNetworkIndex = EMBER_AF_DEFAULT_NETWORK_INDEX
Referenced by emberCommandActionHandler(), and networkSetCommand().
networkCommands
EmberCommandEntry networkCommands[]
Initial value:
= {
  { "form", networkFormCommand, "usv" },
  { "join", networkJoinCommand, "usvu*" },
  { "rejoin", networkRejoinCommand, "uw" },
  { "leave", networkLeaveCommand, "" },
  { "pjoin", networkPermitJoinCommand, "u" },
  { "broad-pjoin", networkPermitJoinCommand, "u" },
  { "extpanid", networkExtendedPanIdCommand, "b" },
  { "find", NULL, (const char *)findCommands },
  emberCommandEntryAction("id",
                          networkIdCommand,
                          "",
                          "Print the current network IDs"),
  { "change-channel", networkChangeChannelCommand, "u" },
  { "multi-phy-start", networkMultiPhyStartCommand, "uusu*" },
  { "multi-phy-stop", networkMultiPhyStopCommand, "" },
  { "set", networkSetCommand, "u" },
  { "change-keep-alive-mode", changeKeepAliveModeCommand, "u" },
  { "timeout-option-mask", networkChangeChildTimeoutOptionMaskCommand, "v" },
  { NULL }
}