Zigbee Application Framework API Reference: option-cli.c File Reference
option-cli.c File Reference
CLI commands various options.
#include "app/framework/util/common.h"
#include "app/framework/security/af-security.h"
#include "app/framework/util/af-main.h"
#include "app/framework/util/service-discovery.h"
#include "app/util/serial/command-interpreter2.h"
Functions
void optionPrintRxCommand (void)
void optionRegisterCommand (void)
void optionDiscoverCommand (void)
void optionBindingTablePrintCommand (void)
void optionBindingTableClearCommand (void)
void optionEndDeviceBindCommand (void)
void optionApsRetryCommand (void)
void optionApsSecurityCommand (void)
void optionLinkCommand (void)
void optionBindingTableSetCommand (void)
void optionPrintRouteCommand (void)
void optionInstallCodeCommand (void)
void optionDiscoveryTargetCommand (void)
void emAfCliServiceDiscoveryCallback (const EmberAfServiceDiscoveryResult *result)
Variables
EmberCommandEntry emAfOptionCommands []
Detailed Description
CLI commands various options.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Function Documentation
emAfCliServiceDiscoveryCallback()
void emAfCliServiceDiscoveryCallback (const EmberAfServiceDiscoveryResult * result)
References EMBER_AF_BROADCAST_SERVICE_DISCOVERY_RESPONSE_RECEIVED, emberAfHaveDiscoveryResponseStatus, IEEE_ADDRESS_REQUEST, EmberAfEndpointList::list, MATCH_DESCRIPTORS_REQUEST, EmberAfServiceDiscoveryResult::matchAddress, NETWORK_ADDRESS_REQUEST, EmberAfServiceDiscoveryResult::responseData, EmberAfServiceDiscoveryResult::status, and EmberAfServiceDiscoveryResult::zdoRequestClusterId.
Referenced by zdoIeeeAddressRequestCommand(), and zdoNwkAddressRequestCommand().
optionApsRetryCommand()
void optionApsRetryCommand (void)
optionApsSecurityCommand()
void optionApsSecurityCommand (void)
optionBindingTableClearCommand()
void optionBindingTableClearCommand (void)
optionBindingTablePrintCommand()
void optionBindingTablePrintCommand (void)
References EmberBindingTableEntry::clusterId, EMBER_MULTICAST_BINDING, EMBER_SUCCESS, EMBER_UNUSED_BINDING, EmberBindingTableEntry::identifier, EmberBindingTableEntry::local, EmberBindingTableEntry::networkIndex, EmberBindingTableEntry::remote, and EmberBindingTableEntry::type.
optionBindingTableSetCommand()
void optionBindingTableSetCommand (void)
References EmberRouteTableEntry::age, EmberBindingTableEntry::clusterId, EmberRouteTableEntry::concentratorType, EmberRouteTableEntry::destination, EMBER_SUCCESS, EMBER_UNICAST_BINDING, emberAfPopNetworkIndex(), emberAfPushEndpointNetworkIndex(), EmberBindingTableEntry::identifier, EmberBindingTableEntry::local, EmberBindingTableEntry::networkIndex, EmberRouteTableEntry::nextHop, optionPrintRouteCommand(), EmberBindingTableEntry::remote, EmberRouteTableEntry::routeRecordState, EmberRouteTableEntry::status, and EmberBindingTableEntry::type.
optionDiscoverCommand()
void optionDiscoverCommand (void)
References emberAfFindDevicesByProfileAndCluster().
optionDiscoveryTargetCommand()
void optionDiscoveryTargetCommand (void)
optionEndDeviceBindCommand()
void optionEndDeviceBindCommand (void)
References emberAfSendEndDeviceBind().
optionInstallCodeCommand()
void optionInstallCodeCommand (void)
References EMBER_BAD_ARGUMENT, EMBER_SECURITY_DATA_INVALID, and EMBER_SUCCESS.
optionLinkCommand()
void optionLinkCommand (void)
optionPrintRouteCommand()
void optionPrintRouteCommand (void)
Referenced by optionBindingTableSetCommand().
optionPrintRxCommand()
void optionPrintRxCommand (void)
optionRegisterCommand()
void optionRegisterCommand (void)
References emberAfRegistrationStartCallback().
Variable Documentation
emAfOptionCommands
EmberCommandEntry emAfOptionCommands[]
Initial value:
= {
  { "print-rx-msgs", NULL, (const char *)optionPrintRxCommands },
  { "register", optionRegisterCommand, "" },
  emberCommandEntryAction("disc", optionDiscoverCommand, "vv",
                          "Perform a match descriptor request"),
  emberCommandEntryAction("target", optionDiscoveryTargetCommand, "v",
                          "Set the target address of the CLI discovery"),
  { "binding-table", NULL, (const char *)optionBindingCommands },
  { "edb", optionEndDeviceBindCommand, "u" },
  { "security", NULL, (const char *)optionSecurityCommands },
  { "apsretry", NULL, (const char *)apsRetryCommands },
  { NULL }
}