Zigbee Application Framework API Reference: security-cli.c File Reference
security-cli.c File Reference
Routines to initiate key establishment, handle key establishment callbacks, and print info about the security keys on the device.
#include "app/framework/util/common.h"
#include "app/framework/util/service-discovery.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/framework/cli/security-cli.h"
#include "app/framework/util/af-main.h"
#include "app/framework/security/af-security.h"
Macros
#define setTcRejoinsUsingWellKnownKeyAllowed(allow) emberSetTcRejoinsUsingWellKnownKeyAllowed((allow))
#define setTcRejoinsUsingWellKnownKeyTimeout(timeout) emAllowTcRejoinsUsingWellKnownKeyTimeoutSec = (timeout)
#define getTransientKeyTableEntry emberGetTransientKeyTableEntry
#define EMBER_AF_DOXYGEN_CLI__SECURITY_CHANGEKEY_COMMANDS
Commands used to change the default link or network key that will be used when forming or joining a network.
#define EMBER_AF_DOXYGEN_CLI__SECURITY_CBKE_COMMANDS
Command used for key establishment.
#define EMBER_AF_DOXYGEN_CLI__SECURITY_MFG_TOKEN_COMMANDS
Commands used for security.
Functions
void getSetMfgToken (void)
uint8_t printKeyTable (bool preconfiguredKey)
uint8_t printTransientKeyTable (void)
uint32_t getOutgoingApsFrameCounter (void)
void changeKeyCommand (void)
void printKeyInfo (void)
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKey (void)
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout (void)
void optionSecuritySetKeyRequestPolicy (void)
Variables
uint16_t emAllowTcRejoinsUsingWellKnownKeyTimeoutSec
EmberKeyData cliPreconfiguredLinkKey = DUMMY_KEY
EmberKeyData cliNetworkKey = DUMMY_KEY
EmberCommandEntry changeKeyCommands []
EmberCommandEntry mfgToken []
EmberCommandEntry emAfSecurityCommands []
Detailed Description
Routines to initiate key establishment, handle key establishment callbacks, and print info about the security keys on the device.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Macro Definition Documentation
getTransientKeyTableEntry
#define getTransientKeyTableEntry emberGetTransientKeyTableEntry
Referenced by printTransientKeyTable().
setTcRejoinsUsingWellKnownKeyAllowed
#define setTcRejoinsUsingWellKnownKeyAllowed (allow) emberSetTcRejoinsUsingWellKnownKeyAllowed((allow))
Referenced by optionSecurityAllowTrustCenterRejoinUsingWellKnownKey().
setTcRejoinsUsingWellKnownKeyTimeout
#define setTcRejoinsUsingWellKnownKeyTimeout (timeout) emAllowTcRejoinsUsingWellKnownKeyTimeoutSec = (timeout)
Referenced by optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout().
Function Documentation
changeKeyCommand()
void changeKeyCommand (void)
References EMBER_NO_NETWORK, and emberAfDebugPrintln.
getOutgoingApsFrameCounter()
uint32_t getOutgoingApsFrameCounter (void)
References EMBER_SUCCESS, EMBER_TRUST_CENTER_LINK_KEY, and EmberKeyStruct::outgoingFrameCounter.
Referenced by printKeyInfo().
getSetMfgToken()
void getSetMfgToken (void)
References EMBER_KEY_PERMISSIONS_HASHING_ALLOWED, EMBER_KEY_PERMISSIONS_READING_ALLOWED, EMBER_SUCCESS, and EmberMfgSecurityStruct::keySettings.
optionSecurityAllowTrustCenterRejoinUsingWellKnownKey()
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKey (void)
References setTcRejoinsUsingWellKnownKeyAllowed.
optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout()
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout (void)
References setTcRejoinsUsingWellKnownKeyTimeout.
optionSecuritySetKeyRequestPolicy()
void optionSecuritySetKeyRequestPolicy (void)
printKeyInfo()
void printKeyInfo (void)
References EMBER_CURRENT_NETWORK_KEY, EMBER_KEY_PERMISSIONS_READING_ALLOWED, EMBER_SUCCESS, emberKeyContents(), getOutgoingApsFrameCounter(), EmberKeyStruct::key, EmberMfgSecurityStruct::keySettings, EmberKeyStruct::outgoingFrameCounter, printKeyTable(), printTransientKeyTable(), and EmberKeyStruct::sequenceNumber.
Referenced by keysPrintCommand().
printKeyTable()
uint8_t printKeyTable (bool preconfiguredKey)
References EmberKeyStruct::bitmask, EMBER_KEY_IS_AUTHORIZED, EMBER_SUCCESS, EMBER_TRUST_CENTER_LINK_KEY, emberKeyContents(), EmberKeyStruct::incomingFrameCounter, EmberKeyStruct::key, and EmberKeyStruct::partnerEUI64.
Referenced by printKeyInfo().
printTransientKeyTable()
uint8_t printTransientKeyTable (void)
References EmberTransientKeyData::bitmask, EMBER_SUCCESS, emberKeyContents(), EmberTransientKeyData::eui64, getTransientKeyTableEntry, EmberTransientKeyData::incomingFrameCounter, EmberTransientKeyData::keyData, EmberTransientKeyData::networkIndex, and EmberTransientKeyData::remainingTimeSeconds.
Referenced by printKeyInfo().
Variable Documentation
changeKeyCommands
EmberCommandEntry changeKeyCommands[]
Initial value:
= {
  { "link", changeKeyCommand, "b" },
  { "network", changeKeyCommand, "b" },
  { NULL }
}
cliNetworkKey
EmberKeyData cliNetworkKey = DUMMY_KEY
cliPreconfiguredLinkKey
EmberKeyData cliPreconfiguredLinkKey = DUMMY_KEY
emAfSecurityCommands
EmberCommandEntry emAfSecurityCommands[]
Initial value:
= {
  emberCommandEntrySubMenu("mfg-token", mfgToken,
                           "Get/set the MFG Security config token"),
  emberCommandEntryTerminator(),
}
emAllowTcRejoinsUsingWellKnownKeyTimeoutSec
uint16_t emAllowTcRejoinsUsingWellKnownKeyTimeoutSec
mfgToken
EmberCommandEntry mfgToken[]
Initial value:
= {
  emberCommandEntryAction("get", getSetMfgToken, "",
                          "Print the MFG security config token"),
  emberCommandEntryAction("set", getSetMfgToken, "wv",
                          "Set the MFG Security config token.  CANNOT BE UNSET BY CLI."),
  emberCommandEntryTerminator(),
}