Zigbee Application Framework API Reference: security-cli.h File Reference
security-cli.h File Reference
Routines to print info about the security keys on the device.
Functions
void changeKeyCommand (void)
void printKeyInfo (void)
Variables
EmberCommandEntry changeKeyCommands []
EmberKeyData cliPreconfiguredLinkKey
EmberKeyData cliNetworkKey
EmberCommandEntry emAfSecurityCommands []
Detailed Description
Routines to print info about the security keys on the device.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Function Documentation
changeKeyCommand()
void changeKeyCommand (void)
References EMBER_NO_NETWORK, and emberAfDebugPrintln.
printKeyInfo()
void printKeyInfo (void)
References EMBER_CURRENT_NETWORK_KEY, EMBER_KEY_PERMISSIONS_READING_ALLOWED, EMBER_SUCCESS, emberKeyContents(), getOutgoingApsFrameCounter(), EmberKeyStruct::key, EmberMfgSecurityStruct::keySettings, EmberKeyStruct::outgoingFrameCounter, printKeyTable(), printTransientKeyTable(), and EmberKeyStruct::sequenceNumber.
Referenced by keysPrintCommand().
Variable Documentation
changeKeyCommands
EmberCommandEntry changeKeyCommands[]
cliNetworkKey
EmberKeyData cliNetworkKey
cliPreconfiguredLinkKey
EmberKeyData cliPreconfiguredLinkKey
emAfSecurityCommands
EmberCommandEntry emAfSecurityCommands[]