Zigbee Application Framework API Reference: zcl-cli.h File Reference
zcl-cli.h File Reference
CLI commands for sending various messages.
Macros
#define zclSimpleClientCommand(clusterId, commandId)
#define zclSimpleServerCommand(clusterId, commandId)
Functions
void emAfCliSendCommand (void)
void emAfCliSendUsingMulticastBindingCommand (void)
void emAfCliBsendCommand (void)
void emAfCliReadCommand (void)
void emAfCliWriteCommand (void)
void emAfCliTimesyncCommand (void)
void emAfCliRawCommand (void)
void emAfCliAddReportEntryCommand (void)
void zclSimpleCommand (uint8_t frameControl, uint16_t clusterId, uint8_t commandId)
Variables
EmberCommandEntry keysCommands []
EmberCommandEntry interpanCommands []
EmberCommandEntry printCommands []
EmberCommandEntry zclCommands []
EmberCommandEntry certificationCommands []
Detailed Description
CLI commands for sending various messages.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Macro Definition Documentation
zclSimpleClientCommand
#define zclSimpleClientCommand (clusterId, commandId)
Value:
zclSimpleCommand(ZCL_CLUSTER_SPECIFIC_COMMAND | ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, \
                   (clusterId),                                                       \
                   (commandId))
Referenced by zclDrlcLoadControlEventCommand(), zclGroupsGetCommand(), zclIdentifyOnOffCommand(), zclTestResponseOffCommand(), and zclTimeCommand().
zclSimpleServerCommand
#define zclSimpleServerCommand (clusterId, commandId)
Value:
zclSimpleCommand(ZCL_CLUSTER_SPECIFIC_COMMAND | ZCL_FRAME_CONTROL_SERVER_TO_CLIENT, \
                   (clusterId),                                                       \
                   (commandId))
Referenced by zclDrlcLoadControlEventCommand(), and zclGroupsGetCommand().
Function Documentation
emAfCliAddReportEntryCommand()
void emAfCliAddReportEntryCommand (void)
emAfCliBsendCommand()
void emAfCliBsendCommand (void)
References EmberApsFrame::clusterId, and zclCmdIsBuilt.
emAfCliRawCommand()
void emAfCliRawCommand (void)
References APP_ZCL_BUFFER_SIZE_CLI, appZclBuffer, emAfApsFrameClusterIdSetup(), and ZCL_MANUFACTURER_SPECIFIC_MASK.
emAfCliReadCommand()
void emAfCliReadCommand (void)
References EMBER_ZCL_STATUS_SUCCESS, emberAfGetDataSize(), emberAfIsLongStringAttributeType(), emberAfIsStringAttributeType(), and emberAfReadAttribute().
emAfCliSendCommand()
void emAfCliSendCommand (void)
References appZclBuffer, appZclBufferLen, disableDefaultResponse, emAfApsFrameEndpointSetup(), EMBER_AF_NULL_MANUFACTURER_CODE, EMBER_APS_OPTION_ENCRYPTION, EMBER_BROADCAST_ADDRESS, EMBER_OUTGOING_DIRECT, EMBER_SUCCESS, emberAfDebugPrintln, emberAfGetNodeId(), emberAfPreCliSendCallback(), emberAfSendBroadcast(), emberAfSendMulticast(), emberAfSendUnicast(), mfgSpecificId, EmberApsFrame::options, and zclCmdIsBuilt.
Referenced by emAfCliTimesyncCommand().
emAfCliSendUsingMulticastBindingCommand()
void emAfCliSendUsingMulticastBindingCommand (void)
emAfCliTimesyncCommand()
void emAfCliTimesyncCommand (void)
References cliBufferPrint(), emAfCliSendCommand(), emAfSyncingTime, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_GLOBAL_COMMAND, zclBufferAddWord(), and zclBufferSetup().
emAfCliWriteCommand()
void emAfCliWriteCommand (void)
References emberAfGetDataSize(), emberAfIsLongStringAttributeType(), emberAfIsStringAttributeType(), and emberAfWriteAttribute().
zclSimpleCommand()
void zclSimpleCommand (uint8_t frameControl, uint16_t clusterId, uint8_t commandId)
References cliBufferPrint(), zclBufferAddByteFromArgument(), zclBufferAddInt16sFromArgument(), zclBufferAddInt32FromArgument(), zclBufferAddInt32sFromArgument(), zclBufferAddInt8sFromArgument(), zclBufferAddLengthAndStringFromArgument(), zclBufferAddWordFromArgument(), and zclBufferSetup().
Variable Documentation
certificationCommands
EmberCommandEntry certificationCommands[]
interpanCommands
EmberCommandEntry interpanCommands[]
keysCommands
EmberCommandEntry keysCommands[]
printCommands
EmberCommandEntry printCommands[]
zclCommands
EmberCommandEntry zclCommands[]