Zigbee Application Framework API Reference: zcl-cli.c File Reference
zcl-cli.c File Reference
CLI commands for sending various messages.
#include "app/framework/util/common.h"
#include "app/framework/util/af-main.h"
#include "app/framework/util/attribute-storage.h"
#include "app/framework/util/service-discovery.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/framework/cli/security-cli.h"
#include "app/util/common/library.h"
Macros
#define APP_ZCL_BUFFER_SIZE EMBER_AF_MAXIMUM_SEND_PAYLOAD_LENGTH
#define APP_ZCL_BUFFER_SIZE_CLI
#define EMBER_AF_DOXYGEN_CLI__ZCL_GLOBAL_COMMANDS
Commands used to send global commands in the zcl.
Functions
void emAfApsFrameEndpointSetup (uint8_t srcEndpoint, uint8_t dstEndpoint)
void emAfApsFrameClusterIdSetup (uint16_t clusterId)
void cliBufferPrint (void)
void emAfCliRawCommand (void)
void zclBufferSetup (uint8_t frameType, uint16_t clusterId, uint8_t commandId)
void zclBufferAddByte (uint8_t byte)
void zclBufferAddWord (uint16_t word)
void zclBufferAddInt32 (uint32_t value)
void zclBufferAddBuffer (const uint8_t *buffer, uint8_t length)
void zclBufferAddString (const uint8_t *buffer)
void zclBufferAddByteFromArgument (uint8_t index)
void zclBufferAddInt8sFromArgument (uint8_t index)
void zclBufferAddInt16sFromArgument (uint8_t index)
void zclBufferAddInt32sFromArgument (uint8_t index)
void zclBufferAddWordFromArgument (uint8_t index)
void zclBufferAddInt32FromArgument (uint8_t index)
void zclBufferAddLengthAndStringFromArgument (uint8_t argIndex)
void zclBufferAddLongLengthAndStringFromArgument (uint8_t argIndex)
void makeZclBuffer (uint8_t frameControl, uint16_t clusterId, uint8_t commandId, char *format,...)
void zclSimpleCommand (uint8_t frameControl, uint16_t clusterId, uint8_t commandId)
void zclGlobalSetup (uint8_t commandId)
void zclGlobalDirectionCommand (void)
void zclGlobalReadCommand (void)
void zclGlobalWriteCommand (void)
void zclGlobalDiscoverCommand (void)
void zclGlobalReportCommand (void)
void zclGlobalReportReadCommand (void)
void zclGlobalSendMeAReportCommand (void)
void zclGlobalExpectReportFromMeCommand (void)
void zclGlobalCommandDiscoveryCommand (void)
void zclTestResponseOnCommand (void)
void zclTestResponseOffCommand (void)
void zclMfgCodeCommand (void)
void zclXDefaultRespCommand (void)
void zclUseNextSequenceCommand (void)
void zclTimeCommand (void)
void zclIdentifyOnOffCommand (void)
void zclGroupsGetCommand (void)
void zclDrlcLoadControlEventCommand (void)
void emAfCliSendCommand (void)
void emAfCliSendUsingMulticastBindingCommand (void)
void emAfCliBsendCommand (void)
void emAfCliTimesyncCommand (void)
void interpanCommand (void)
void interpanLongCommand (void)
void printTimeCommand (void)
void emAfCliReadCommand (void)
void emAfCliWriteCommand (void)
void eraseKeyTableEntry (uint8_t index)
void keysClearCommand (void)
void keysPrintCommand (void)
void keysDeleteCommand (void)
Variables
uint8_t appZclBuffer [APP_ZCL_BUFFER_SIZE]
uint16_t appZclBufferLen
bool zclCmdIsBuilt = false
uint16_t mfgSpecificId = EMBER_AF_NULL_MANUFACTURER_CODE
uint8_t disableDefaultResponse = 0
EmberApsFrame globalApsFrame
bool emAfSyncingTime
EmberCommandEntry zclGlobalCommands []
EmberCommandEntry zclTestResponseCommands []
EmberCommandEntry zclTestCommands []
EmberCommandEntry zclMessageCommands []
EmberCommandEntry zclCommands []
EmberCommandEntry keysCommands []
EmberCommandEntry printCommands []
EmberCommandEntry interpanCommands []
Detailed Description
CLI commands for sending various messages.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Macro Definition Documentation
APP_ZCL_BUFFER_SIZE
#define APP_ZCL_BUFFER_SIZE EMBER_AF_MAXIMUM_SEND_PAYLOAD_LENGTH
Referenced by zclDrlcLoadControlEventCommand(), and zclGlobalReportCommand().
APP_ZCL_BUFFER_SIZE_CLI
#define APP_ZCL_BUFFER_SIZE_CLI
Value:
(APP_ZCL_BUFFER_SIZE > 255    \
   ? 255                        \
   : APP_ZCL_BUFFER_SIZE)
Referenced by emAfCliRawCommand().
Function Documentation
cliBufferPrint()
void cliBufferPrint (void)
References appZclBuffer, appZclBufferLen, EmberApsFrame::clusterId, ZCL_MANUFACTURER_SPECIFIC_MASK, and zclCmdIsBuilt.
Referenced by emAfCliTimesyncCommand(), keysDeleteCommand(), makeZclBuffer(), zclDrlcLoadControlEventCommand(), zclGlobalDiscoverCommand(), zclGlobalReadCommand(), zclGlobalReportCommand(), zclGroupsGetCommand(), zclIdentifyOnOffCommand(), and zclSimpleCommand().
emAfApsFrameClusterIdSetup()
void emAfApsFrameClusterIdSetup (uint16_t clusterId)
References EmberApsFrame::clusterId, and EmberApsFrame::options.
Referenced by emAfCliRawCommand(), and zclBufferSetup().
emAfApsFrameEndpointSetup()
void emAfApsFrameEndpointSetup (uint8_t srcEndpoint, uint8_t dstEndpoint)
References EmberApsFrame::destinationEndpoint, emberAfPrimaryEndpointForCurrentNetworkIndex(), and EmberApsFrame::sourceEndpoint.
Referenced by emAfCliSendCommand().
emAfCliBsendCommand()
void emAfCliBsendCommand (void)
References EmberApsFrame::clusterId, and zclCmdIsBuilt.
emAfCliRawCommand()
void emAfCliRawCommand (void)
References APP_ZCL_BUFFER_SIZE_CLI, appZclBuffer, emAfApsFrameClusterIdSetup(), and ZCL_MANUFACTURER_SPECIFIC_MASK.
emAfCliReadCommand()
void emAfCliReadCommand (void)
References EMBER_ZCL_STATUS_SUCCESS, emberAfGetDataSize(), emberAfIsLongStringAttributeType(), emberAfIsStringAttributeType(), and emberAfReadAttribute().
emAfCliSendCommand()
void emAfCliSendCommand (void)
References appZclBuffer, appZclBufferLen, disableDefaultResponse, emAfApsFrameEndpointSetup(), EMBER_AF_NULL_MANUFACTURER_CODE, EMBER_APS_OPTION_ENCRYPTION, EMBER_BROADCAST_ADDRESS, EMBER_OUTGOING_DIRECT, EMBER_SUCCESS, emberAfDebugPrintln, emberAfGetNodeId(), emberAfPreCliSendCallback(), emberAfSendBroadcast(), emberAfSendMulticast(), emberAfSendUnicast(), mfgSpecificId, EmberApsFrame::options, and zclCmdIsBuilt.
Referenced by emAfCliTimesyncCommand().
emAfCliSendUsingMulticastBindingCommand()
void emAfCliSendUsingMulticastBindingCommand (void)
emAfCliTimesyncCommand()
void emAfCliTimesyncCommand (void)
References cliBufferPrint(), emAfCliSendCommand(), emAfSyncingTime, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_GLOBAL_COMMAND, zclBufferAddWord(), and zclBufferSetup().
emAfCliWriteCommand()
void emAfCliWriteCommand (void)
References emberAfGetDataSize(), emberAfIsLongStringAttributeType(), emberAfIsStringAttributeType(), and emberAfWriteAttribute().
eraseKeyTableEntry()
void eraseKeyTableEntry (uint8_t index)
References EMBER_SUCCESS.
Referenced by keysClearCommand(), and keysDeleteCommand().
interpanCommand()
void interpanCommand (void)
References appZclBuffer, appZclBufferLen, EmberAfInterpanHeader::clusterId, EmberApsFrame::clusterId, EMBER_SUCCESS, emberAfDebugPrintln, emberAfInterpanSendMessageCallback(), EmberAfInterpanHeader::groupId, EmberAfInterpanHeader::panId, EmberAfInterpanHeader::profileId, EmberAfInterpanHeader::shortAddress, and zclCmdIsBuilt.
interpanLongCommand()
void interpanLongCommand (void)
References appZclBuffer, appZclBufferLen, EmberAfInterpanHeader::clusterId, EmberApsFrame::clusterId, EMBER_AF_INTERPAN_OPTION_MAC_HAS_LONG_ADDRESS, EMBER_SUCCESS, emberAfDebugPrintln, emberAfInterpanSendMessageCallback(), EmberAfInterpanHeader::longAddress, EmberAfInterpanHeader::options, EmberAfInterpanHeader::panId, EmberAfInterpanHeader::profileId, and zclCmdIsBuilt.
keysClearCommand()
void keysClearCommand (void)
References eraseKeyTableEntry().
keysDeleteCommand()
void keysDeleteCommand (void)
References cliBufferPrint(), eraseKeyTableEntry(), ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_GLOBAL_COMMAND, zclBufferAddWord(), and zclBufferSetup().
keysPrintCommand()
void keysPrintCommand (void)
References printKeyInfo().
makeZclBuffer()
void makeZclBuffer (uint8_t frameControl, uint16_t clusterId, uint8_t commandId, char * format, ...)
References cliBufferPrint(), zclBufferAddBuffer(), zclBufferAddByte(), zclBufferAddInt32(), zclBufferAddWord(), and zclBufferSetup().
printTimeCommand()
void printTimeCommand (void)
zclBufferAddBuffer()
void zclBufferAddBuffer (const uint8_t * buffer, uint8_t length)
References appZclBuffer, and appZclBufferLen.
Referenced by makeZclBuffer(), and zclBufferAddString().
zclBufferAddByte()
void zclBufferAddByte (uint8_t byte)
References appZclBuffer, and appZclBufferLen.
Referenced by makeZclBuffer(), zclBufferAddByteFromArgument(), zclBufferAddInt32(), zclBufferAddInt8sFromArgument(), zclBufferAddWord(), zclDrlcLoadControlEventCommand(), zclGlobalReportCommand(), zclGroupsGetCommand(), and zclIdentifyOnOffCommand().
zclBufferAddByteFromArgument()
void zclBufferAddByteFromArgument (uint8_t index)
References zclBufferAddByte().
Referenced by zclGroupsGetCommand(), and zclSimpleCommand().
zclBufferAddInt16sFromArgument()
void zclBufferAddInt16sFromArgument (uint8_t index)
References zclBufferAddWord().
Referenced by zclSimpleCommand().
zclBufferAddInt32()
void zclBufferAddInt32 (uint32_t value)
References zclBufferAddByte().
Referenced by makeZclBuffer(), zclBufferAddInt32FromArgument(), zclBufferAddInt32sFromArgument(), and zclDrlcLoadControlEventCommand().
zclBufferAddInt32FromArgument()
void zclBufferAddInt32FromArgument (uint8_t index)
References zclBufferAddInt32().
Referenced by zclGroupsGetCommand(), and zclSimpleCommand().
zclBufferAddInt32sFromArgument()
void zclBufferAddInt32sFromArgument (uint8_t index)
References zclBufferAddInt32().
Referenced by zclSimpleCommand().
zclBufferAddInt8sFromArgument()
void zclBufferAddInt8sFromArgument (uint8_t index)
References zclBufferAddByte().
Referenced by zclSimpleCommand().
zclBufferAddLengthAndStringFromArgument()
void zclBufferAddLengthAndStringFromArgument (uint8_t argIndex)
Referenced by zclGroupsGetCommand(), and zclSimpleCommand().
zclBufferAddLongLengthAndStringFromArgument()
void zclBufferAddLongLengthAndStringFromArgument (uint8_t argIndex)
zclBufferAddString()
void zclBufferAddString (const uint8_t * buffer)
References emberAfStringLength(), and zclBufferAddBuffer().
zclBufferAddWord()
void zclBufferAddWord (uint16_t word)
References zclBufferAddByte().
Referenced by emAfCliTimesyncCommand(), keysDeleteCommand(), makeZclBuffer(), zclBufferAddInt16sFromArgument(), zclBufferAddWordFromArgument(), zclGlobalReportCommand(), and zclGroupsGetCommand().
zclBufferAddWordFromArgument()
void zclBufferAddWordFromArgument (uint8_t index)
References zclBufferAddWord().
Referenced by zclDrlcLoadControlEventCommand(), zclGroupsGetCommand(), zclIdentifyOnOffCommand(), and zclSimpleCommand().
zclBufferSetup()
void zclBufferSetup (uint8_t frameType, uint16_t clusterId, uint8_t commandId)
References appZclBuffer, appZclBufferLen, disableDefaultResponse, emAfApsFrameClusterIdSetup(), EMBER_AF_NULL_MANUFACTURER_CODE, emberAfNextSequence(), mfgSpecificId, ZCL_DISABLE_DEFAULT_RESPONSE_MASK, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, and ZCL_MANUFACTURER_SPECIFIC_MASK.
Referenced by emAfCliTimesyncCommand(), keysDeleteCommand(), makeZclBuffer(), zclDrlcLoadControlEventCommand(), zclGlobalCommandDiscoveryCommand(), zclGlobalExpectReportFromMeCommand(), zclGlobalReportCommand(), zclGlobalReportReadCommand(), zclGlobalSendMeAReportCommand(), zclGlobalSetup(), zclGroupsGetCommand(), zclIdentifyOnOffCommand(), and zclSimpleCommand().
zclDrlcLoadControlEventCommand()
void zclDrlcLoadControlEventCommand (void)
References APP_ZCL_BUFFER_SIZE, appZclBuffer, appZclBufferLen, cliBufferPrint(), EMBER_APS_OPTION_SOURCE_EUI64, EmberApsFrame::options, ZCL_CLUSTER_SPECIFIC_COMMAND, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_FRAME_CONTROL_SERVER_TO_CLIENT, zclBufferAddByte(), zclBufferAddInt32(), zclBufferAddWordFromArgument(), zclBufferSetup(), zclSimpleClientCommand, and zclSimpleServerCommand.
Referenced by zclGroupsGetCommand().
zclGlobalCommandDiscoveryCommand()
void zclGlobalCommandDiscoveryCommand (void)
References ZCL_GLOBAL_COMMAND, and zclBufferSetup().
zclGlobalDirectionCommand()
void zclGlobalDirectionCommand (void)
zclGlobalDiscoverCommand()
void zclGlobalDiscoverCommand (void)
References cliBufferPrint(), and zclGlobalSetup().
zclGlobalExpectReportFromMeCommand()
void zclGlobalExpectReportFromMeCommand (void)
References ZCL_GLOBAL_COMMAND, and zclBufferSetup().
zclGlobalReadCommand()
void zclGlobalReadCommand (void)
References cliBufferPrint(), and zclGlobalSetup().
zclGlobalReportCommand()
void zclGlobalReportCommand (void)
References APP_ZCL_BUFFER_SIZE, appZclBuffer, appZclBufferLen, cliBufferPrint(), EMBER_ZCL_STATUS_SUCCESS, emberAfAttributeValueSize(), emberAfReadAttribute(), ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_FRAME_CONTROL_SERVER_TO_CLIENT, ZCL_GLOBAL_COMMAND, zclBufferAddByte(), zclBufferAddWord(), and zclBufferSetup().
zclGlobalReportReadCommand()
void zclGlobalReportReadCommand (void)
References ZCL_GLOBAL_COMMAND, and zclBufferSetup().
zclGlobalSendMeAReportCommand()
void zclGlobalSendMeAReportCommand (void)
References ZCL_GLOBAL_COMMAND, and zclBufferSetup().
zclGlobalSetup()
void zclGlobalSetup (uint8_t commandId)
References ZCL_GLOBAL_COMMAND, and zclBufferSetup().
Referenced by zclGlobalDiscoverCommand(), zclGlobalReadCommand(), and zclGlobalWriteCommand().
zclGlobalWriteCommand()
void zclGlobalWriteCommand (void)
References emberAfIsThisDataTypeAStringType(), and zclGlobalSetup().
zclGroupsGetCommand()
void zclGroupsGetCommand (void)
References cliBufferPrint(), EMBER_APS_OPTION_SOURCE_EUI64, EmberApsFrame::options, ZCL_CLUSTER_SPECIFIC_COMMAND, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_FRAME_CONTROL_SERVER_TO_CLIENT, zclBufferAddByte(), zclBufferAddByteFromArgument(), zclBufferAddInt32FromArgument(), zclBufferAddLengthAndStringFromArgument(), zclBufferAddWord(), zclBufferAddWordFromArgument(), zclBufferSetup(), zclDrlcLoadControlEventCommand(), zclSimpleClientCommand, and zclSimpleServerCommand.
Referenced by zclIdentifyOnOffCommand().
zclIdentifyOnOffCommand()
void zclIdentifyOnOffCommand (void)
References cliBufferPrint(), ZCL_CLUSTER_SPECIFIC_COMMAND, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, zclBufferAddByte(), zclBufferAddWordFromArgument(), zclBufferSetup(), zclGroupsGetCommand(), and zclSimpleClientCommand.
Referenced by zclTimeCommand().
zclMfgCodeCommand()
void zclMfgCodeCommand (void)
References mfgSpecificId, and zclCmdIsBuilt.
zclSimpleCommand()
void zclSimpleCommand (uint8_t frameControl, uint16_t clusterId, uint8_t commandId)
References cliBufferPrint(), zclBufferAddByteFromArgument(), zclBufferAddInt16sFromArgument(), zclBufferAddInt32FromArgument(), zclBufferAddInt32sFromArgument(), zclBufferAddInt8sFromArgument(), zclBufferAddLengthAndStringFromArgument(), zclBufferAddWordFromArgument(), and zclBufferSetup().
zclTestResponseOffCommand()
void zclTestResponseOffCommand (void)
References zclSimpleClientCommand.
zclTestResponseOnCommand()
void zclTestResponseOnCommand (void)
zclTimeCommand()
void zclTimeCommand (void)
References EMBER_ZCL_STATUS_SUCCESS, emberAfDebugPrintln, emberAfWriteServerAttribute(), zclIdentifyOnOffCommand(), and zclSimpleClientCommand.
zclUseNextSequenceCommand()
void zclUseNextSequenceCommand (void)
zclXDefaultRespCommand()
void zclXDefaultRespCommand (void)
References disableDefaultResponse.
Variable Documentation
appZclBuffer
uint8_t appZclBuffer[APP_ZCL_BUFFER_SIZE]
Referenced by cliBufferPrint(), emAfCliRawCommand(), emAfCliSendCommand(), interpanCommand(), interpanLongCommand(), zclBufferAddBuffer(), zclBufferAddByte(), zclBufferSetup(), zclDrlcLoadControlEventCommand(), and zclGlobalReportCommand().
appZclBufferLen
uint16_t appZclBufferLen
Referenced by cliBufferPrint(), emAfCliSendCommand(), interpanCommand(), interpanLongCommand(), zclBufferAddBuffer(), zclBufferAddByte(), zclBufferSetup(), zclDrlcLoadControlEventCommand(), and zclGlobalReportCommand().
disableDefaultResponse
uint8_t disableDefaultResponse = 0
Referenced by emAfCliSendCommand(), zclBufferSetup(), and zclXDefaultRespCommand().
emAfSyncingTime
bool emAfSyncingTime
Referenced by emAfCliTimesyncCommand().
globalApsFrame
EmberApsFrame globalApsFrame
interpanCommands
EmberCommandEntry interpanCommands[]
Initial value:
= {
  { "group", interpanCommand, "vvv" },
  { "short", interpanCommand, "vvv" },
  { "long", interpanLongCommand, "bvvv" },
  { NULL }
}
keysCommands
EmberCommandEntry keysCommands[]
Initial value:
= {
  emberCommandEntryAction("clear", keysClearCommand, "", "Clear all link keys"),
  emberCommandEntryAction("print", keysPrintCommand, "", "Print the NWK and link key table"),
  emberCommandEntryAction("delete", keysDeleteCommand, "u", "Delete the specified link key index"),
  emberCommandEntryTerminator(),
}
mfgSpecificId
uint16_t mfgSpecificId = EMBER_AF_NULL_MANUFACTURER_CODE
Referenced by emAfCliSendCommand(), zclBufferSetup(), and zclMfgCodeCommand().
printCommands
EmberCommandEntry printCommands[]
Initial value:
= {
  emberCommandEntryAction("time", printTimeCommand, "", "Print current time attribute"),
  emberCommandEntryAction("attr", emberAfPrintAttributeTable, "", "Print the attribute table"),
  emberCommandEntryTerminator(),
}
zclCmdIsBuilt
bool zclCmdIsBuilt = false
Referenced by cliBufferPrint(), emAfCliBsendCommand(), emAfCliSendCommand(), interpanCommand(), interpanLongCommand(), and zclMfgCodeCommand().
zclCommands
EmberCommandEntry zclCommands[]
zclGlobalCommands
EmberCommandEntry zclGlobalCommands[]
Initial value:
= {
  { "read", zclGlobalReadCommand, "vv" },
  { "write", zclGlobalWriteCommand, "vvub" },
  { "uwrite", zclGlobalWriteCommand, "vvub" },
  { "nwrite", zclGlobalWriteCommand, "vvub" },
  { "discover", zclGlobalDiscoverCommand, "vvu" },
  { "report-read", zclGlobalReportReadCommand, "vvu" },
  { "send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb" },
  { "expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv" },
  { "report", zclGlobalReportCommand, "uvvu" },
  { "direction", zclGlobalDirectionCommand, "u" },
  { "disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu" },
  { "disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu" },
  { NULL }
}
zclMessageCommands
EmberCommandEntry zclMessageCommands[]
Initial value:
= {
  { NULL }
}
zclTestCommands
EmberCommandEntry zclTestCommands[]
Initial value:
= {
  { "response", NULL, (const char *)zclTestResponseCommands },
  { NULL }
}
zclTestResponseCommands
EmberCommandEntry zclTestResponseCommands[]
Initial value:
= {
  { "on", zclTestResponseOnCommand, "" },
  { "off", zclTestResponseOffCommand, "" },
  { NULL }
}