Zigbee Application Framework API Reference: zdo-cli.c File Reference
zdo-cli.c File Reference
CLI commands for sending ZDO messages.
#include "app/framework/util/common.h"
#include "app/framework/util/af-main.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/util/zigbee-framework/zigbee-device-common.h"
#include "app/util/zigbee-framework/zigbee-device-library.h"
#include "app/framework/cli/option-cli.h"
Macros
#define MAX_CLUSTERS_CAN_MATCH 5
Functions
void zdoNwkAddressRequestCommand (void)
void zdoIeeeAddressRequestCommand (void)
void zdoSimpleCommand (void)
void zdoNodeCommand (void)
void zdoMatchCommand (void)
void zdoBindCommand (void)
void zdoAddClusterCommand (void)
void zdoClearClusterCommand (void)
void zdoNetworkUpdateChannelCommand (void)
void zdoNetworkUpdateScanCommand (void)
void zdoNetworkUpdateSetCommand (void)
void zdoActiveEpCommand (void)
void zdoMgmtLqiCommand (void)
void zdoMgmtBindCommand (void)
EmberStatus matchDescriptorsRequest (EmberNodeId target, uint16_t profile, uint8_t inCount, uint8_t outCount, uint16_t *inClusters, uint16_t *outClusters, EmberApsOption options)
void zdoLeaveRequestCommand (void)
void zdoPowerDescriptorRequestCommand (void)
void zdoEndDeviceBindRequestCommand (void)
void zdoUnbindGroupCommand (void)
void zdoUnbindUnicastCommand (void)
void zdoRouteRequestCommand (void)
Variables
EmberCommandEntry zdoCommands []
uint16_t emAfCliZdoInClusters [MAX_CLUSTERS_CAN_MATCH]
uint16_t emAfCliZdoOutClusters [MAX_CLUSTERS_CAN_MATCH]
uint8_t emAfCliInClCount = 0
uint8_t emAfCliOutClCount = 0
Detailed Description
CLI commands for sending ZDO messages.
License
Copyright 2018 Silicon Laboratories Inc. www.silabs.com
The licensor of this software is Silicon Laboratories Inc. Your use of this software is governed by the terms of Silicon Labs Master Software License Agreement (MSLA) available at www.silabs.com/about-us/legal/master-software-license-agreement. This software is distributed to you in Source Code format and is governed by the sections of the MSLA applicable to Source Code.
Macro Definition Documentation
MAX_CLUSTERS_CAN_MATCH
#define MAX_CLUSTERS_CAN_MATCH 5
Referenced by zdoAddClusterCommand().
Function Documentation
matchDescriptorsRequest()
EmberStatus matchDescriptorsRequest (EmberNodeId target, uint16_t profile, uint8_t inCount, uint8_t outCount, uint16_t * inClusters, uint16_t * outClusters, EmberApsOption options)
References EMBER_NO_BUFFERS, and EMBER_SUCCESS.
Referenced by zdoMatchCommand(), and zdoRouteRequestCommand().
zdoActiveEpCommand()
void zdoActiveEpCommand (void)
References EMBER_APS_OPTION_RETRY.
zdoAddClusterCommand()
void zdoAddClusterCommand (void)
References emAfCliInClCount, emAfCliOutClCount, emAfCliZdoInClusters, emAfCliZdoOutClusters, and MAX_CLUSTERS_CAN_MATCH.
zdoBindCommand()
void zdoBindCommand (void)
References EMBER_SUCCESS.
zdoClearClusterCommand()
void zdoClearClusterCommand (void)
References emAfCliInClCount, and emAfCliOutClCount.
zdoEndDeviceBindRequestCommand()
void zdoEndDeviceBindRequestCommand (void)
References emberAfSendEndDeviceBind().
zdoIeeeAddressRequestCommand()
void zdoIeeeAddressRequestCommand (void)
References emAfCliServiceDiscoveryCallback(), and emberAfFindIeeeAddress().
zdoLeaveRequestCommand()
void zdoLeaveRequestCommand (void)
References EMBER_APS_OPTION_RETRY, and EMBER_ZIGBEE_LEAVE_AND_REJOIN.
zdoMatchCommand()
void zdoMatchCommand (void)
References emAfCliInClCount, emAfCliOutClCount, emAfCliZdoInClusters, emAfCliZdoOutClusters, and matchDescriptorsRequest().
zdoMgmtBindCommand()
void zdoMgmtBindCommand (void)
References EMBER_APS_OPTION_RETRY.
zdoMgmtLqiCommand()
void zdoMgmtLqiCommand (void)
References EMBER_APS_OPTION_RETRY.
zdoNetworkUpdateChannelCommand()
void zdoNetworkUpdateChannelCommand (void)
References EMBER_NO_CHANNEL_PAGE_IN_USE, EMBER_SLEEPY_BROADCAST_ADDRESS, and EMBER_SUCCESS.
zdoNetworkUpdateScanCommand()
void zdoNetworkUpdateScanCommand (void)
References EMBER_ALL_802_15_4_CHANNELS_MASK.
zdoNetworkUpdateSetCommand()
void zdoNetworkUpdateSetCommand (void)
zdoNodeCommand()
void zdoNodeCommand (void)
zdoNwkAddressRequestCommand()
void zdoNwkAddressRequestCommand (void)
References emAfCliServiceDiscoveryCallback(), and emberAfFindNodeId().
zdoPowerDescriptorRequestCommand()
void zdoPowerDescriptorRequestCommand (void)
References EMBER_APS_OPTION_RETRY.
zdoRouteRequestCommand()
void zdoRouteRequestCommand (void)
References EMBER_APS_OPTION_RETRY, and matchDescriptorsRequest().
zdoSimpleCommand()
void zdoSimpleCommand (void)
zdoUnbindGroupCommand()
void zdoUnbindGroupCommand (void)
zdoUnbindUnicastCommand()
void zdoUnbindUnicastCommand (void)
References emberAfGetEui64().
Variable Documentation
emAfCliInClCount
uint8_t emAfCliInClCount = 0
Referenced by zdoAddClusterCommand(), zdoClearClusterCommand(), and zdoMatchCommand().
emAfCliOutClCount
uint8_t emAfCliOutClCount = 0
Referenced by zdoAddClusterCommand(), zdoClearClusterCommand(), and zdoMatchCommand().
emAfCliZdoInClusters
uint16_t emAfCliZdoInClusters[MAX_CLUSTERS_CAN_MATCH]
Referenced by zdoAddClusterCommand(), and zdoMatchCommand().
emAfCliZdoOutClusters
uint16_t emAfCliZdoOutClusters[MAX_CLUSTERS_CAN_MATCH]
Referenced by zdoAddClusterCommand(), and zdoMatchCommand().
zdoCommands
EmberCommandEntry zdoCommands[]