from pyradioconfig.parts.ocelot.phys.Phys_Studio_Base_Standard_SUNFSK import PHYS_Studio_Base_Standard_SUNFSK_Ocelot

class PHYS_Studio_Base_Standard_SUNFSK_Sol(PHYS_Studio_Base_Standard_SUNFSK_Ocelot):
    pass