<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.efm32.efm32gg12.port" label="Port" name="Port" description="" version="A">
    <properties/>
    <propertyCategories>
      <category label="Port Bank">
        <subCategory label=""/>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
